# Generated by Django 6.1.1 on 2026-10-04 15:18

import django.db.models.deletion
import taller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono"
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.BigIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Telegram (chat)",
                    ),
                ),
                (
                    "link_token",
                    models.CharField(
                        default=taller.models.new_link_token,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PriceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Nombre tal como lo escribe el programa. Ej.: "aceite motor" (precio por litro)',
                        max_length=80,
                        unique=True,
                        verbose_name="recambio",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="precio sin IVA"
                    ),
                ),
            ],
            options={
                "verbose_name": "tarifa de recambio",
                "verbose_name_plural": "tarifas de recambios",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                (
                    "plate",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="matrícula"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        help_text='Escríbelo como en papel. Ej.: "cambio aceite motor opel aceite 5w30"',
                        verbose_name="qué hay que hacer",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="servicio"
                    ),
                ),
                (
                    "vehicle",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="vehículo"
                    ),
                ),
                (
                    "parts",
                    models.JSONField(
                        blank=True, default=list, verbose_name="recambios"
                    ),
                ),
                (
                    "repeat_months",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = no se repite",
                        verbose_name="se repite cada (meses)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pendiente", "Pendiente"), ("hecha", "Hecha")],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                (
                    "ordered",
                    models.BooleanField(
                        default=False, verbose_name="recambios pedidos"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="taller.client",
                        verbose_name="cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "cita",
                "verbose_name_plural": "citas",
                "ordering": ["date", "id"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, unique=True, verbose_name="número"),
                ),
                ("created_at", models.DateField(verbose_name="fecha")),
                ("lines", models.JSONField(verbose_name="líneas")),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="IVA"
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="taller.appointment",
                        verbose_name="cita",
                    ),
                ),
            ],
            options={
                "verbose_name": "factura",
                "verbose_name_plural": "facturas",
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(max_length=30, verbose_name="proveedor/canal"),
                ),
                ("parts", models.JSONField(verbose_name="recambios")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="enviado"),
                ),
                (
                    "detail",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="detalle"
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="taller.appointment",
                        verbose_name="cita",
                    ),
                ),
            ],
            options={
                "verbose_name": "pedido",
                "verbose_name_plural": "pedidos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("send_on", models.DateField(verbose_name="enviar el")),
                ("message", models.TextField(verbose_name="mensaje")),
                ("sent", models.BooleanField(default=False, verbose_name="enviado")),
                (
                    "detail",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="detalle"
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taller.appointment",
                        verbose_name="cita origen",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taller.client",
                        verbose_name="cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "aviso",
                "verbose_name_plural": "avisos",
                "ordering": ["send_on"],
            },
        ),
    ]
