# Generated by Django 6.1.1 on 2026-10-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taller", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="order_error",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="último error del pedido"
            ),
        ),
    ]
