# Generated by Django 6.1.1 on 2026-10-04 19:42

from django.db import migrations, models


def initial_rates(apps, schema_editor):
    LaborRate = apps.get_model("taller", "LaborRate")
    for service, price in [("cambio de aceite", "45.00"), ("ITV", "30.00"), ("cambio de neumáticos", "40.00")]:
        LaborRate.objects.get_or_create(service=service, defaults={"price": price})


class Migration(migrations.Migration):

    dependencies = [
        ("taller", "0002_order_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaborRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        help_text='Como lo entiende el programa. Ej.: "cambio de aceite"',
                        max_length=120,
                        unique=True,
                        verbose_name="trabajo",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="mano de obra (sin IVA)",
                    ),
                ),
            ],
            options={
                "verbose_name": "tarifa de mano de obra",
                "verbose_name_plural": "tarifas de mano de obra",
                "ordering": ["service"],
            },
        ),
        migrations.DeleteModel(
            name="PriceItem",
        ),
        migrations.RunPython(initial_rates, migrations.RunPython.noop),
    ]
